#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance 	 true
bspc config history_aware_focus  true
bspc config focused_border_color \#8ec07c
bspc config normal_border_color  \#427b58
bspc config top_padding 10
bspc config focus_follows_pointer true
